import Image from "next/image";
import "../styles/globals.css";
import Alarm from "@/components/Alarm/Alarm";
import PrimaryButton from "@/components/Button/PrimaryButton";
import NationaFlag from "@/components/NationalFlag/NationaFlag";
import Link from "next/link";
import Search from "@/components/SearchBar/Search";
import { menuItems } from "@/constants/nav";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between min-h-screen bg-gray-200/50">
        <Header menuItems={menuItems} />
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
